version: 3
endpoint: https://getting-started-mqm.hasura.app
admin_secret: ${PROD.HASURA_ADMIN_SECRET}
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
